---
galaxy_info:
  role_name: lighthouse_role
  author: valdemar-2502
  description: Role for LightHouse and Nginx installation
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: EL
      versions:
        - "8"
dependencies: []
