---
- name: Create vector directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ vector_install_dir }}"
    - "{{ vector_config_dir }}"

- name: Get vector distrib
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-x86_64-unknown-linux-gnu.tar.gz"
    dest: "/tmp/vector-{{ vector_version }}.tar.gz"
    mode: '0644'

- name: Unarchive vector
  ansible.builtin.unarchive:
    src: "/tmp/vector-{{ vector_version }}.tar.gz"
    dest: "{{ vector_install_dir }}"
    remote_src: true
    extra_opts: [--strip-components=1]

- name: Create symlink for vector binary
  ansible.builtin.file:
    src: "{{ vector_install_dir }}/bin/vector"
    dest: "/usr/local/bin/vector"
    state: link
    force: true

- name: Deploy Vector config
  ansible.builtin.template:
    src: vector.toml.j2
    dest: "{{ vector_config_dir }}/vector.toml"
    mode: '0644'
  notify: Restart vector

- name: Create vector systemd service
  ansible.builtin.copy:
    dest: /etc/systemd/system/vector.service
    content: |
      [Unit]
      Description=Vector
      Documentation=https://vector.dev
      After=network-online.target
      Requires=network-online.target

      [Service]
      User=root
      Group=root
      ExecStart=/usr/local/bin/vector --config /etc/vector/vector.toml
      Restart=always

      [Install]
      WantedBy=multi-user.target
    mode: '0644'

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true

- name: Ensure vector service is running
  ansible.builtin.service:
    name: vector
    state: started
    enabled: true
